# Generated by Django 5.2.6 on 2025-09-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='static/images/foto_perfil.jpg', upload_to='static/uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='link_project',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(default='Sem tags.', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(default='Sem tipos.', max_length=50),
            preserve_default=False,
        ),
    ]
