# Generated by Django 5.2.6 on 2025-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(default='sem_video.mp4', upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
