# Generated by Django 5.2.6 on 2025-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_thumbnail_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='Sem thumbnail', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
