# Generated by Django 5.2.6 on 2025-09-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_name_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
