# Generated by Django 5.2.6 on 2025-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_thumbnail_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(upload_to='static/uploads'),
        ),
    ]
