# Generated by Django 5.2.6 on 2025-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='static/uploads')),
                ('thumbnail', models.ImageField(upload_to='static/uploads')),
                ('tools', models.CharField(max_length=300)),
                ('link_project', models.URLField(
                    blank=True, max_length=300, null=True)),
                ('type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
