# Generated by Django 5.2.6 on 2025-10-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_tags_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
