# Generated by Django 5.2.6 on 2025-09-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tools',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
